---
# tasks file for code_manager/roles/update_tower_template

- name: "Grab {{ template_name }} Template ID"
  uri:
    url:              "https://{{ tower_fqdn }}/api/v2/job_templates/"
    method:           GET
    force_basic_auth: true
    validate_certs:   false
    user:             "{{ tower_username }}"
    password:         "{{ tower_password }}"
  register:           temp_id

- set_fact:
    template_id:      "{{ temp_id | json_query(query) | first }}"
    project_id:       "{{ temp_id | json_query(queryp) | first }}"
    inventory_id:     "{{ temp_id | json_query(queryi) | first }}"
  vars:
    query:            "json.results[?name=='{{ template_name }}'].id"
    queryp:           "json.results[?summary_fields.project.name=='{{ project_name }}'].summary_fields.project.id"
    queryi:           "json.results[?summary_fields.inventory.name=='{{ inventory_name }}'].summary_fields.inventory.id"

- name: "Update the {{ template_name }} template"
  uri:
    url:              "https://{{ tower_fqdn }}/api/v2/job_templates/40/"
    method:           PATCH
    force_basic_auth: true
    validate_certs:   false
    body_format:      json
    user:             "{{ tower_username }}"
    password:         "{{ tower_password }}"
    name:             "cibc"
    body:
      name:        "{{ template_name }}"
      inventory:   "{{ inventory_id }}"
      verbosity:   "{{ verbosity_level | default(0)}}"
      project:     "{{ project_id }}"
      job_type:    "{{ job_type | default('run') }}"
      playbook:    "{{ playbook_name | default('main.yml') }}"
      job_tags:    "{{ job_tags | default('') }}"
