---
- name: 'Grab the ID for the inventory'
  uri:
    url:              "https://{{ tower_fqdn }}/api/v2/inventories/?name={{ tower_inventory_name }}"
    user:             "{{ tower_username }}"
    password:         "{{ tower_password }}"
    method:           GET
    force_basic_auth: true
    status_code:      200
    validate_certs:   false
  register: inventory_id_response

- set_fact:
    inventory_id: "{{ (inventory_id_response.json.results | first)['id'] }}"
  when:
    - (inventory_id_response.json.results | length == 1)

- name: 'Create the inventory, it does not exist' 
  uri:
    url:               "https://{{ tower_fqdn }}/api/v2/inventories/"
    user:              "{{ tower_username }}"
    password:          "{{ tower_password }}"
    method:            POST
    body:
      name:            "{{ tower_inventory_name }}"
      organization:    "{{ tower_organization_id }}"
      description:     "{{ tower_description }}"
    force_basic_auth:  true
    status_code:       201
    body_format:       json
    validate_certs:    false
  changed_when:        true
  register: new_inventory_id_response 
  when:
    - (inventory_id_response.json.results | length < 1)
    - (inventory_id is undefined)

- set_fact:
    inventory_id: "{{ new_inventory_id_response.json['id'] }}"
  when:
    - inventory_id is undefined

