---
- name: 'get the current credential if it exists'
  uri:
    url:              "https://{{ tower_fqdn }}/api/v2/credentials/?name={{ credential_name }}"
    user:             "{{ tower_username }}"
    password:         "{{ tower_password }}"
    method:           GET
    force_basic_auth: true
    status_code:      200
    validate_certs:   false
  register: tower_credentials_response

- set_fact:
    tower_machine_credential_id: "{{ (tower_credentials_response.json.results | first)['id'] }}"
  when:
    - (tower_credentials_response.json.results | length == 1)

- name: 'create tower machine credential used for ssh connectivity to managed hosts'
  uri:
    url:               "https://{{ tower_fqdn }}/api/v2/credentials/"
    user:              "{{ tower_username }}"
    password:          "{{ tower_password }}"
    method:            POST
    body:
      credential_type: "{{ credential_type_id }}"
      name:            "{{ credential_name }}"
      user:            1
      inputs:
        username: "{{ ssh_default_username }}"
        password: "{{ ssh_default_password }}"
    force_basic_auth:  true
    status_code:       201
    body_format:       json
    validate_certs:    false
  changed_when:        true
  register: tower_create_machine_credential_response
  when:
    - (tower_credentials_response.json.results | length < 1)
    - (tower_machine_credential_id is undefined)

- name: 'set a fact with the credential id'
  set_fact:
    tower_machine_credential_id: "{{ tower_create_machine_credential_response.json['id'] }}"
  when:
    - tower_machine_credential_id is undefined
